# Generated by Django 5.0.6 on 2024-07-20 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
